version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install -r requirements.txt/common.txt

  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - python manage.py test

artifacts:
  type: zip
  files:
    - 'user'
    - 'website/**/*'
    - 'myapp/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
    - 'manage.py'
    - 'requirements.txt'
    - 'supervisord.conf'

