version: '3'
services:
  app:
    build: .
    volumes :
      - dbdata:/var/lib/mysql
    networks:
    - main  # Add the container to the network "main"
    depends_on:
    - db
  db:
    container_name: MYSQL
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: MYSQldjangodocker_db
      MYSQL_ROOT_PASSWORD: root
      ports:
        — "3306:3306"
networks:
  main:



